### ISSUE TITLE
Multiselect bug

### ISSUE THREAD

**Issue by red17electro** [stryberventures/stryber-react-ui-components-v2#155]
Hey guys, 

I am trying to use multi-select from GAIA, but experiencing issues with a thrown error:

```
index.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'secondary')
    at index.js:1:3640
    at index.js:1:4319
    at getStyles2 (react-jss.esm.js:150:10)
    at createStyleSheet2 (react-jss.esm.js:191:16)
    at react-jss.esm.js:300:22
    at mountMemo (react-dom.development.js:17225:19)
    at Object.useMemo (react-dom.development.js:17670:16)
    at useMemo (react.development.js:1650:21)
    at useStyles (react-jss.esm.js:299:20)
    at u (index.js:1:4949)
```
![multiselect](https://user-images.githubusercontent.com/16454623/215065710-abcfea2a-e2f7-4b64-afb6-e8887412b795.gif)

Usage:

```
              <Multiselect
                  label="Multiselect"
                  color='secondary'
                  options={[
                    {label: 'Option 1', value: 'option1'},
                    {label: 'Option 2', value: 'option2'},
                    {label: 'Option 3', value: 'option3'},
                    {label: 'Option 4', value: 'option4'},
                    {label: 'Option 5', value: 'option5'},
                  ]}
                  placeholder="Select an option"
              />
```

Components version:

```
    "@stryberventures/gaia-react.button": "^0.0.4",
    "@stryberventures/gaia-react.checkbox": "^0.0.4",
    "@stryberventures/gaia-react.chip": "^0.0.4",
    "@stryberventures/gaia-react.combobox": "^0.0.2",
    "@stryberventures/gaia-react.dropdown": "^0.0.5",
    "@stryberventures/gaia-react.form": "^0.0.3",
    "@stryberventures/gaia-react.input": "^0.0.5",
    "@stryberventures/gaia-react.input-password": "^0.0.4",
    "@stryberventures/gaia-react.multiselect": "^0.0.5",
    "@stryberventures/gaia-react.select": "^0.0.4",
    "@stryberventures/gaia-react.text": "^0.0.2",
    "@stryberventures/gaia-react.text-link": "^0.0.4",
    "@stryberventures/gaia-react.theme": "^0.0.3",
```

Not sure if it is related to theme object, mine it's very similar to the one in Storybook though:

```
const theme = {
  colors: {
    primary: {
      dark600: '#001D9A',
      main500: '#0029DB',
      medium400: '#3D61FF',
      medium300: '#607EFF',
      light200: '#A7B7FF',
      light100: '#CAD4FF',
      extraLight50: '#EDF1FF'
    },
    secondary: {
      dark600: '#3A1F7A',
      main500: '#532CAE',
      medium400: '#8664D8',
      medium300: '#9C80DF',
      light200: '#BDAAEA',
      light100: '#DED5F4',
      extraLight50: '#F4F1FB'
    },
    neutralGray: {
      extraDark900: '#101828',
      extraDark800: '#1D2939',
      dark700: '#344054',
      dark600: '#475467',
      main500: '#667085',
      medium400: '#98A2B3',
      medium300: '#D0D5DD',
      light200: '#E4E7EC',
      light100: '#F2F4F7',
      extraLight50: '#F9FAFB'
    },
    text: {
      headline: '#101828',
      secondary: '#475467',
      disabled: '#D0D5DD',
      tint: '#98A2B3'
    },
    background: {
      white: '#FFFFFF',
      extraLightGrey: '#F9FAFB'
    },
    success: {
      dark600: '#006644',
      main500: '#00875A',
      medium400: '#36A176',
      medium300: '#57D9A3',
      light200: '#79F2C0',
      light100: '#ABF5D1',
      extraLight50: '#E3FCEF'
    },
    warning: {
      dark600: '#FF8B00',
      main500: '#FF991F',
      medium400: '#FFAB00',
      medium300: '#FFC400',
      light200: '#FFE380',
      light100: '#FFF0B3',
      extraLight50: '#FFFAE6'
    },
    contrast: {
      white: '#FFFFFF',
      black: '#000000'
    },
  },
...
};
```

**Comment by red17electro** [comment]
Update: looks like I found what was causing the issue. 

I had to install `"@stryberventures/gaia-react.input-toggle-layout"` as a dependency, which was not mentioned in the documentation for Multiselect (please add it, thanks!).

![Screenshot 2023-01-27 at 14 54 29](https://user-images.githubusercontent.com/16454623/215103575-64b87d50-ae4f-45ce-9d4e-72ddaf027374.png)

However, now I am experiencing another issue with lack of options for the direction in which dropdown opens. Ideally, would be great to have it opened to the 'top' direction, especially if there is no space below. Please check the screenshot:

![Screenshot 2023-01-27 at 14 57 26](https://user-images.githubusercontent.com/16454623/215104163-1cf5205d-6e2f-45b2-8f62-227db59e7e03.png)

As you see, dropdown is opened, but not really visible. I cannot scroll either, as scroll of the pop-up is behind the overlay of the dropdown.

**Comment by SergeySychevskiy** [comment]
Hey Server. Thanks for sharing this issue with us. 
From what I see - you use Material UI Dialog, which has overflow and that's the reason why Multiselect content is cropped. Ideally, we should have a possibility to render the content in Portal, then such issue won't appear. We agreed with the team that we will add such functionality later, but for now there are 2 options:
- remove overflow from MUI Dialog
- use GAIA Dialog component.
